### ISSUE TITLE
Text on home page

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#115]
The below text should go only to the **employer** home page, not on the primary home page.

Please replace as below :
![Screen Shot 2019-07-31 at 5 15 22 PM](https://user-images.githubusercontent.com/30720308/62209286-d1652f80-b3b6-11e9-8c03-6dffdc4bbd5b.png)

New text 

Never miss a job alert!
<CTA Start now> (navigate to sign in page)

**Comment by lvlnsiva** [comment]
fixed

**Comment by Mythri295** [comment]
@lvlnsiva I still see the same content.

![Screen Shot 2019-08-02 at 2 50 02 PM](https://user-images.githubusercontent.com/30720308/62359704-f97a9d00-b534-11e9-9a9e-76710fc7688a.png)


Pls replace the text :

**_Never miss a job alert!_**
(navigate to sign in page)

**Comment by lvlnsiva** [comment]
Its fixed for employer tab

**Comment by lvlnsiva** [comment]
For normal skillpad home tab it will come like above

**Comment by Mythri295** [comment]
I am saying, we can't show this text to a job seeker. It should be shown only on the employer home page. you need to add the below text for the primary page (skillpad.co)

Never miss a job alert! (pls use this text and replace looking to hire recruitment consultant)

this should be the text on https://www.skillpad.co/

**Comment by lvlnsiva** [comment]
![Screen Shot 2019-08-03 at 8 48 47 PM](https://user-images.githubusercontent.com/5269744/62414982-76df0400-b640-11e9-8f50-794bd85b465f.png)
![Screen Shot 2019-08-03 at 8 49 42 PM](https://user-images.githubusercontent.com/5269744/62414983-76df0400-b640-11e9-955b-6af45e71644f.png)
![Screen Shot 2019-08-03 at 8 49 59 PM](https://user-images.githubusercontent.com/5269744/62414984-76df0400-b640-11e9-86e3-e8ffb9a2303e.png)
